### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by Samiepapa** [Samiepapa/pifuhd#1]
```
$ sh ./scripts/demo.sh
Traceback (most recent call last):
  File "/home/yongilcho/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yongilcho/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yongilcho/reposit/pifuhd/apps/simple_test.py", line 4, in <module>
    from .recon import reconWrapper
  File "/home/yongilcho/reposit/pifuhd/apps/recon.py", line 18, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
freeglut (foo): failed to open display ''
```

**Comment by Samiepapa** [comment]
matplotlib 설치해서 해결
```
$ pip3 install matplotlib
Collecting matplotlib
  Downloading matplotlib-3.5.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 11.0 MB/s eta 0:00:00
Requirement already satisfied: pillow>=6.2.0 in /home/yongilcho/.virtualenvs/pifuhd/lib/python3.8/site-packages (from matplotlib) (9.0.1)
Requirement already satisfied: packaging>=20.0 in /home/yongilcho/.virtualenvs/pifuhd/lib/python3.8/site-packages (from matplotlib) (21.3)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: pyparsing>=2.2.1 in /home/yongilcho/.virtualenvs/pifuhd/lib/python3.8/site-packages (from matplotlib) (3.0.7)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 10.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /home/yongilcho/.virtualenvs/pifuhd/lib/python3.8/site-packages (from matplotlib) (1.22.2)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.29.1-py3-none-any.whl (895 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 895.5/895.5 KB 8.1 MB/s eta 0:00:00
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, kiwisolver, fonttools, cycler, python-dateutil, matplotlib
Successfully installed cycler-0.11.0 fonttools-4.29.1 kiwisolver-1.3.2 matplotlib-3.5.1 python-dateutil-2.8.2 six-1.16.0
```
